// Created by Autokaka (qq1909698494@gmail.com) on 2024/02/23.

#include <unordered_map>

#include "seen/mod/gpu_texture_format.h"

namespace seen::mod {

TGPUTextureFormat GPUTextureFormat::From(const WGPUTextureFormat& format) {
  static std::unordered_map<WGPUTextureFormat, TGPUTextureFormat> kWGPUToTextureFormat = {
      {WGPUTextureFormat_R8Unorm, GPUTextureFormat::kR8Unorm},
      {WGPUTextureFormat_R8Snorm, GPUTextureFormat::kR8Snorm},
      {WGPUTextureFormat_R8Uint, GPUTextureFormat::kR8Uint},
      {WGPUTextureFormat_R8Sint, GPUTextureFormat::kR8Sint},
      {WGPUTextureFormat_R16Uint, GPUTextureFormat::kR16Uint},
      {WGPUTextureFormat_R16Sint, GPUTextureFormat::kR16Sint},
      {WGPUTextureFormat_R16Float, GPUTextureFormat::kR16Float},
      {WGPUTextureFormat_RG8Unorm, GPUTextureFormat::kRG8Unorm},
      {WGPUTextureFormat_RG8Snorm, GPUTextureFormat::kRG8Snorm},
      {WGPUTextureFormat_RG8Uint, GPUTextureFormat::kRG8Uint},
      {WGPUTextureFormat_RG8Sint, GPUTextureFormat::kRG8Sint},
      {WGPUTextureFormat_R32Float, GPUTextureFormat::kR32Float},
      {WGPUTextureFormat_R32Uint, GPUTextureFormat::kR32Uint},
      {WGPUTextureFormat_R32Sint, GPUTextureFormat::kR32Sint},
      {WGPUTextureFormat_RG16Uint, GPUTextureFormat::kRG16Uint},
      {WGPUTextureFormat_RG16Sint, GPUTextureFormat::kRG16Sint},
      {WGPUTextureFormat_RG16Float, GPUTextureFormat::kRG16Float},
      {WGPUTextureFormat_RGBA8Unorm, GPUTextureFormat::kRGBA8Unorm},
      {WGPUTextureFormat_RGBA8UnormSrgb, GPUTextureFormat::kRGBA8UnormSrgb},
      {WGPUTextureFormat_RGBA8Snorm, GPUTextureFormat::kRGBA8Snorm},
      {WGPUTextureFormat_RGBA8Uint, GPUTextureFormat::kRGBA8Uint},
      {WGPUTextureFormat_RGBA8Sint, GPUTextureFormat::kRGBA8Sint},
      {WGPUTextureFormat_BGRA8Unorm, GPUTextureFormat::kBGRA8Unorm},
      {WGPUTextureFormat_BGRA8UnormSrgb, GPUTextureFormat::kBGRA8UnormSrgb},
      {WGPUTextureFormat_RGB10A2Uint, GPUTextureFormat::kRGB10A2Uint},
      {WGPUTextureFormat_RGB10A2Unorm, GPUTextureFormat::kRGB10A2Unorm},
      {WGPUTextureFormat_RG11B10Ufloat, GPUTextureFormat::kRG11B10Ufloat},
      {WGPUTextureFormat_RGB9E5Ufloat, GPUTextureFormat::kRGB9E5Ufloat},
      {WGPUTextureFormat_RG32Float, GPUTextureFormat::kRG32Float},
      {WGPUTextureFormat_RG32Uint, GPUTextureFormat::kRG32Uint},
      {WGPUTextureFormat_RG32Sint, GPUTextureFormat::kRG32Sint},
      {WGPUTextureFormat_RGBA16Uint, GPUTextureFormat::kRGBA16Uint},
      {WGPUTextureFormat_RGBA16Sint, GPUTextureFormat::kRGBA16Sint},
      {WGPUTextureFormat_RGBA16Float, GPUTextureFormat::kRGBA16Float},
      {WGPUTextureFormat_RGBA32Float, GPUTextureFormat::kRGBA32Float},
      {WGPUTextureFormat_RGBA32Uint, GPUTextureFormat::kRGBA32Uint},
      {WGPUTextureFormat_RGBA32Sint, GPUTextureFormat::kRGBA32Sint},
      {WGPUTextureFormat_Stencil8, GPUTextureFormat::kStencil8},
      {WGPUTextureFormat_Depth16Unorm, GPUTextureFormat::kDepth16Unorm},
      {WGPUTextureFormat_Depth24Plus, GPUTextureFormat::kDepth24Plus},
      {WGPUTextureFormat_Depth24PlusStencil8, GPUTextureFormat::kDepth24PlusStencil8},
      {WGPUTextureFormat_Depth32Float, GPUTextureFormat::kDepth32Float},
      {WGPUTextureFormat_Depth32FloatStencil8, GPUTextureFormat::kDepth32FloatStencil8},
      {WGPUTextureFormat_BC1RGBAUnorm, GPUTextureFormat::kBC1RGBAUnorm},
      {WGPUTextureFormat_BC1RGBAUnormSrgb, GPUTextureFormat::kBC1RGBAUnormSrgb},
      {WGPUTextureFormat_BC2RGBAUnorm, GPUTextureFormat::kBC2RGBAUnorm},
      {WGPUTextureFormat_BC2RGBAUnormSrgb, GPUTextureFormat::kBC2RGBAUnormSrgb},
      {WGPUTextureFormat_BC3RGBAUnorm, GPUTextureFormat::kBC3RGBAUnorm},
      {WGPUTextureFormat_BC3RGBAUnormSrgb, GPUTextureFormat::kBC3RGBAUnormSrgb},
      {WGPUTextureFormat_BC4RUnorm, GPUTextureFormat::kBC4RUnorm},
      {WGPUTextureFormat_BC4RSnorm, GPUTextureFormat::kBC4RSnorm},
      {WGPUTextureFormat_BC5RGUnorm, GPUTextureFormat::kBC5RGUnorm},
      {WGPUTextureFormat_BC5RGSnorm, GPUTextureFormat::kBC5RGSnorm},
      {WGPUTextureFormat_BC6HRGBUfloat, GPUTextureFormat::kBC6HRGBUfloat},
      {WGPUTextureFormat_BC6HRGBFloat, GPUTextureFormat::kBC6HRGBFloat},
      {WGPUTextureFormat_BC7RGBAUnorm, GPUTextureFormat::kBC7RGBAUnorm},
      {WGPUTextureFormat_BC7RGBAUnormSrgb, GPUTextureFormat::kBC7RGBAUnormSrgb},
      {WGPUTextureFormat_ETC2RGB8Unorm, GPUTextureFormat::kETC2RGB8Unorm},
      {WGPUTextureFormat_ETC2RGB8UnormSrgb, GPUTextureFormat::kETC2RGB8UnormSrgb},
      {WGPUTextureFormat_ETC2RGB8A1Unorm, GPUTextureFormat::kETC2RGB8A1Unorm},
      {WGPUTextureFormat_ETC2RGB8A1UnormSrgb, GPUTextureFormat::kETC2RGB8A1UnormSrgb},
      {WGPUTextureFormat_ETC2RGBA8Unorm, GPUTextureFormat::kETC2RGBA8Unorm},
      {WGPUTextureFormat_ETC2RGBA8UnormSrgb, GPUTextureFormat::kETC2RGBA8UnormSrgb},
      {WGPUTextureFormat_EACR11Unorm, GPUTextureFormat::kEACR11Unorm},
      {WGPUTextureFormat_EACR11Snorm, GPUTextureFormat::kEACR11Snorm},
      {WGPUTextureFormat_EACRG11Unorm, GPUTextureFormat::kEACRG11Unorm},
      {WGPUTextureFormat_EACRG11Snorm, GPUTextureFormat::kEACRG11Snorm},
      {WGPUTextureFormat_ASTC4x4Unorm, GPUTextureFormat::kASTC4x4Unorm},
      {WGPUTextureFormat_ASTC4x4UnormSrgb, GPUTextureFormat::kASTC4x4UnormSrgb},
      {WGPUTextureFormat_ASTC5x4Unorm, GPUTextureFormat::kASTC5x4Unorm},
      {WGPUTextureFormat_ASTC5x4UnormSrgb, GPUTextureFormat::kASTC5x4UnormSrgb},
      {WGPUTextureFormat_ASTC5x5Unorm, GPUTextureFormat::kASTC5x5Unorm},
      {WGPUTextureFormat_ASTC5x5UnormSrgb, GPUTextureFormat::kASTC5x5UnormSrgb},
      {WGPUTextureFormat_ASTC6x5Unorm, GPUTextureFormat::kASTC6x5Unorm},
      {WGPUTextureFormat_ASTC6x5UnormSrgb, GPUTextureFormat::kASTC6x5UnormSrgb},
      {WGPUTextureFormat_ASTC6x6Unorm, GPUTextureFormat::kASTC6x6Unorm},
      {WGPUTextureFormat_ASTC6x6UnormSrgb, GPUTextureFormat::kASTC6x6UnormSrgb},
      {WGPUTextureFormat_ASTC8x5Unorm, GPUTextureFormat::kASTC8x5Unorm},
      {WGPUTextureFormat_ASTC8x5UnormSrgb, GPUTextureFormat::kASTC8x5UnormSrgb},
      {WGPUTextureFormat_ASTC8x6Unorm, GPUTextureFormat::kASTC8x6Unorm},
      {WGPUTextureFormat_ASTC8x6UnormSrgb, GPUTextureFormat::kASTC8x6UnormSrgb},
      {WGPUTextureFormat_ASTC8x8Unorm, GPUTextureFormat::kASTC8x8Unorm},
      {WGPUTextureFormat_ASTC8x8UnormSrgb, GPUTextureFormat::kASTC8x8UnormSrgb},
      {WGPUTextureFormat_ASTC10x5Unorm, GPUTextureFormat::kASTC10x5Unorm},
      {WGPUTextureFormat_ASTC10x5UnormSrgb, GPUTextureFormat::kASTC10x5UnormSrgb},
      {WGPUTextureFormat_ASTC10x6Unorm, GPUTextureFormat::kASTC10x6Unorm},
      {WGPUTextureFormat_ASTC10x6UnormSrgb, GPUTextureFormat::kASTC10x6UnormSrgb},
      {WGPUTextureFormat_ASTC10x8Unorm, GPUTextureFormat::kASTC10x8Unorm},
      {WGPUTextureFormat_ASTC10x8UnormSrgb, GPUTextureFormat::kASTC10x8UnormSrgb},
      {WGPUTextureFormat_ASTC10x10Unorm, GPUTextureFormat::kASTC10x10Unorm},
      {WGPUTextureFormat_ASTC10x10UnormSrgb, GPUTextureFormat::kASTC10x10UnormSrgb},
      {WGPUTextureFormat_ASTC12x10Unorm, GPUTextureFormat::kASTC12x10Unorm},
      {WGPUTextureFormat_ASTC12x10UnormSrgb, GPUTextureFormat::kASTC12x10UnormSrgb},
      {WGPUTextureFormat_ASTC12x12Unorm, GPUTextureFormat::kASTC12x12Unorm},
      {WGPUTextureFormat_ASTC12x12UnormSrgb, GPUTextureFormat::kASTC12x12UnormSrgb},
  };
  return kWGPUToTextureFormat[format];
}

}  // namespace seen::mod
