if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
  set(SEEN_BUILD_TYPE "Debug")
  set(SEEN_BUILD_DEBUG ON)
  add_compile_definitions(SEEN_BUILD_DEBUG=1)
elseif(${CMAKE_BUILD_TYPE} STREQUAL "RelWithDebInfo")
  set(SEEN_BUILD_TYPE "Profile")
  set(SEEN_BUILD_PROFILE ON)
  set(SEEN_BUILD_NDEBUG ON)
  add_compile_definitions(SEEN_BUILD_NDEBUG=1)
  add_compile_definitions(SEEN_BUILD_PROFILE=1)
else()
  set(SEEN_BUILD_TYPE "Release")
  set(SEEN_BUILD_RELEASE ON)
  set(SEEN_BUILD_NDEBUG ON)
  add_compile_definitions(SEEN_BUILD_NDEBUG=1)
  add_compile_definitions(SEEN_BUILD_RELEASE=1)
endif()

if(APPLE)
  set(SEEN_BUILD_DARWIN ON)
  add_compile_definitions(SEEN_BUILD_DARWIN=1)
  if (IOS)
    set(SEEN_BUILD_IOS ON)
    set(SEEN_OS_NAME "iOS")
    add_compile_definitions(SEEN_BUILD_IOS=1)
  else()
    set(SEEN_BUILD_MACOS ON)
    set(SEEN_OS_NAME "macOS")
    add_compile_definitions(SEEN_BUILD_MACOS=1)
  endif()
endif(APPLE)

if(ANDROID)
  set(SEEN_BUILD_ANDROID ON)
  set(SEEN_OS_NAME "Android")
  add_compile_definitions(SEEN_BUILD_ANDROID=1)
endif()

set(SEEN_VERSION "SeenKit-v${PROJECT_VERSION}-${SEEN_OS_NAME}-${SEEN_BUILD_TYPE}")
add_compile_definitions(SEEN_VERSION=${SEEN_VERSION})
